default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: dashboard_development

test:
  <<: *default
  database: dashboard_test

production:
  <<: *default
  database: dashboard_production
  username: dashboard
  password: <%= ENV['DASHBOARD_DATABASE_PASSWORD'] %>
