# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bacdd14b5983b457df7fc2a9149dec608a7c023db5a84116154612b916ec6ad1efc07433a3900af10bd4c0432049c8758e4d85863bc627d9b832d4c63046475

test:
  secret_key_base: bfd44d1e72b352806356338e6588dcef1c1f3675faf5599c5d2cffac5a4c603be8d028b4266a5887d0b9642728f396cd96394652c1c1e3159d8be793c83203e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
